"""addhistory

Revision ID: 202a93fb3354
Revises: fae9d79dd0fb
Create Date: 2023-03-28 10:29:15.128749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202a93fb3354'
down_revision = 'fae9d79dd0fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'students', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    # ### end Alembic commands ###
