"""test

Revision ID: 262e6b620753
Revises: e516dbab3143
Create Date: 2023-03-28 08:58:39.722807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262e6b620753'
down_revision = 'e516dbab3143'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'students', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    # ### end Alembic commands ###
