"""update table

Revision ID: 30db56df819a
Revises: a837ffdbbb79
Create Date: 2023-03-27 18:09:24.407242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30db56df819a'
down_revision = 'a837ffdbbb79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'teacher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacher', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
