"""work

Revision ID: 993148d9b081
Revises: b4026b7383ab
Create Date: 2023-03-28 16:11:19.912970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993148d9b081'
down_revision = 'b4026b7383ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
