"""update table

Revision ID: a837ffdbbb79
Revises: f6b7ce7fcab3
Create Date: 2023-03-27 16:22:53.163194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a837ffdbbb79'
down_revision = 'f6b7ce7fcab3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacher', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'teacher')
    # ### end Alembic commands ###
