"""add courses table

Revision ID: f6b7ce7fcab3
Revises: a2ad34e4832f
Create Date: 2023-03-27 15:30:36.946002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b7ce7fcab3'
down_revision = 'a2ad34e4832f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
