"""regenerated tables with alembic

Revision ID: f9b0a9687810
Revises: 1b7c528476f5
Create Date: 2023-03-30 15:49:34.362700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b0a9687810'
down_revision = '1b7c528476f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
